name: Basic Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
      skill:
        description: "Your top skill to share"
        required: true
        default: "Machine Learning"
        type: string
      language:
        description: "Are you great? (true/false)"
        required: true
        type: boolean

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: |
          echo "Hello ${{ github.event.inputs.name }}" 
          echo "Your top skill is ${{ github.event.inputs.skill }}"
          echo "Are you great? Answer: ${{ github.event.inputs.language }}"
